### ISSUE TITLE
프로젝트 DB 접속 방법

### ISSUE THREAD

**Issue by ggujin** [antiquers/theAntiquersRoom#1]
## Overview 
- 프로젝트 DB 접속 방법 소개 

## Detail

1. MySQL Workbench 다운로드
https://dev.mysql.com/downloads/file/?id=507344
접속 후 로그인& 회원가입 하지 말고 
No thanks, just start my download.
클릭하여 다운

2. Connections 추가
![image](https://user-images.githubusercontent.com/76861827/140603756-76dcecd0-0996-47c9-8651-c1238dea709d.png)
하단에 + 버튼 누르기

3.  DB정보 입력
![image](https://user-images.githubusercontent.com/76861827/140603799-b909a528-e2bf-4578-a6a7-bdcc1e72b33a.png)

- Connection Name: antiquers
- Hostname : antiquers.czeunykbiyt3.ap-northeast-2.rds.amazonaws.com
- Username : admin
- Password : antiquers

**Comment by hayo01** [comment]
Windows용 : https://dev.mysql.com/downloads/workbench/

**Comment by kimdindoo** [comment]
pom.xml 에서 marian jdbc jar파일 받고,

		<!— MariaDB JDBC  —>
		<dependency>
		<groupId>org.mariadb.jdbc</groupId>
		<artifactId>mariadb-java-client</artifactId>
		<version>2.6.2</version>
		</dependency>


root-context 에서 마리아 디비 연결하기!

	<!— HikariCP 라이브러리를 이용한, 데이터소스 설정 —>
	<bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
		<description>이 빈의 설명을 넣어라!!!</description>

		<property
				name="driverClassName"
				value="org.mariadb.jdbc.Driver"/>

		<property
				name="jdbcUrl"
				value="jdbc:mariadb://antiquers.czeunykbiyt3.ap-northeast-2.rds.amazonaws.com:3306"/>

		<property name="username" value="admin"/>
		<property name="password" value="antiquers"/>
