### ISSUE TITLE
User 테이블 컬럼 추가 안건(카카오 로그인 API관련)

### ISSUE THREAD

**Issue by gombibi** [antiquers/theAntiquersRoom#39]
## 요약
User 테이블에 kakao_unique_id 컬럼 추가

## 상세 내용
카카오 api를 통한 로그인 시 받을 수 있는 카카오 계정 ID를 이용하여,
해당 ID로 서비스 가입여부를 판단하고,
미가입 회원이면 회원가입페이지로 이동시키고,
기존 가입 회원이면 메인 페이지로 이동시키고자 합니다.

User 테이블의 유저타입 컬럼에 '카카오를 통한 가입회원'을 구분할 수 있는 값(3)도 추가되며,
일반 회원일 경우 kakao_unique_id는 null값 입니다.

<진행 예정 쿼리>
ALTER TABLE users ADD kakao_unique_id VARCHAR(50)

## 관련 이슈
#27

**Comment by gombibi** [comment]
일반회원은 null값이 발생한다는 점이 걸리긴 하는데.. 이대로 진행해도 괜찮을지 의견주숑!!

**Comment by ggujin** [comment]
회원타입에 지금처럼 숫자 말궁 [관리자] [일반회원] [카카오회원] 이렇게 enum으로 들어가면 안되낭,,? 음,, 어렵네 내일 만나서 얘기해보까 ㅠㅠ

**Comment by gombibi** [comment]
@ggujin 조아! 얘기해봅시당 ㅎㅎ
